name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        
      - name: Install Tauri requirements # https://tauri.app/v1/guides/getting-started/prerequisites/#1-system-dependencies
        run: sudo apt update &&
              sudo apt install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
      
      - name: Build
        working-directory: tauri-app/src-tauri
        run: cargo build --verbose
      
      - name: Test
        working-directory: tauri-app/src-tauri
        run: cargo test --verbose
